name: docs-ci

on:
  pull_request:
    paths:
      - 'docs-site/**'
      - 'docs/**'
      - 'openapi/**'
      - 'schemas/**'
      - 'package.json'
  push:
    branches: [ main ]
    paths:
      - 'docs-site/**'
      - 'docs/**'
      - 'openapi/**'
      - 'schemas/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install Dependencies
        run: npm ci

      - name: Validate OpenAPI
        run: npm run openapi:validate

      - name: Build Docs
        run: npm run docs:build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs-site/build
